# This is a basic workflow to help you get started with Actions

name: My First Test Project

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dev-*", "feature/**" ]
  pull_request:
    branches: [ "main", "release-*", "release/**" ]
    types: [review_requested, opened, edited, closed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!  
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Build Steps completed successfully!
      # Archive artifacts 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-app
          path: web.html
            
  Deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy app
        run: echo "This will Deploy APP ..."
      - name: Download web-app artifact
        uses: actions/download-artifact@v4       
        with:
          name: web-app
      - name: Listing artifacts
        run: echo "Listing artifacts generated from build job ..."           
      - name: verify-artifacts
        run: ls -altr
          
