name: Maven Build and Upload JAR

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: check branch
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        echo "This job is running in Main branch"

    - name: Check Branch Main
      if: github.ref == 'refs/heads/main'
      run: echo "Current Branch is main"

    - name: Display Branch Name other
      if: github.ref != 'refs/heads/main'
      run: echo "Current Branch is not on Main"

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn clean package

    - name: Run tests
      run: mvn test

    - name: Upload Job artifacts
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ github.sha }}.jar
        path: target/*.jar
        retention-days: 7

  report:
    needs: 
      - build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: job output info
        run: |
          echo "All jobs completed successfully"
          echo "${{ toJSON(github) }}"


