name: Compile and Save Java Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Compile Java
      run: javac Test.java
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: HelloWorld
        path: HelloWorld.class
