name: Compile and Save Java Artifact

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Compile Code
      run: javac HelloWorld.java
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: JavaArtifacts
        path: HelloWorld.class

    - name: Run Tests
      run: |
        wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.8.2/junit-platform-console-standalone-1.8.2.jar
        java -jar junit-platform-console-standalone-1.8.2.jar -cp . --select-class HelloWorldTest
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorld
        path: |
          HelloWorld.class
          HelloWorldTest.class 
