name: workflow-metadata
on: [push, workflow_dispatch]
jobs:
  workflow-metadata-job:
    runs-on: ubuntu-latest
    steps:
      - name: metadata-output
        run: echo "gitlab metadata output - ${{ toJSON(github) }}"
      - name: welcome msg
        run: echo "Hello world .."      
