name: Reusable template

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: my template job output 
      run: echo "Hello from templates ..."
