name: Reusable workflow template call job
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build job
        run: echo "Build app"
      - name: deploy job 
        uses: ./.github/workflows/template.yml
